{% set name = "ckzg" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ckzg-{{ version }}.tar.gz
  sha256: 62c5adc381637affa7e1df465c57750b356a761b8a3164c3106589b02532b9c9
  patches:
    - setup.py.patch

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - make
    - {{ compiler('clang') }}
    - {{ stdlib('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - libblst
    - libblst-headers
    - setuptools
  run:
    - python
    - libblst

test:
  imports:
    - ckzg
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ethereum/c-kzg-4844
  summary: Python bindings for C-KZG-4844
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - step21
    - MementoRC
