{% set name = "ckzg" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ckzg-{{ version }}.tar.gz
  sha256: 4295acc380f8d42ebea4a4a0a68c424a322bb335a33bad05c72ead8cbb28d118
  patches:
    - setup.py.patch

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - make
    - {{ compiler('clang') }}
    - {{ stdlib('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - libblst
    - libblst-headers
  run:
    - python
    - libblst

test:
  imports:
    - ckzg
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ethereum/c-kzg-4844
  summary: Python bindings for C-KZG-4844
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - step21
    - MementoRC
